# yaml-language-server: $schema=https://unpkg.com/graphql-config@3.3.0/config-schema.json

projects:
  v7:
    schema: "./packages/v7/schema.graphql"
    documents: "./packages/v7/graphql/**/*.graphql"
