name: Validate schemas

on:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate V7 schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: "main:packages/v7/schema.graphql"
